name: 'Example of Custom Action'
description: 'Get weather by input city'
inputs:
  open_weather_key:
    description: 'Open Weather API Key'
    required: true
  city_name:
    description: 'City Name'
    required: false
    default: 'Paris'
outputs:
  weather:
    description: 'Whether'
runs:
  using: 'docker'
  image: 'Dockerfile'